-- SQLite
insert into season (year, nb_of_round) values (2022, 9);
insert into team (name , logo,base,main_color,second_color) values ('BBRFC Celtic','https://admin.touch-belgium.be/media/team_logos/bbrfcceltic_logo.png','Ixelles','#1a2857','#00984b');
insert into team (name , logo,base,main_color,second_color) values ('Boitsfort RC','https://admin.touch-belgium.be/media/team_logos/boitsfort_logo.jpg','Boitsfort','#1e3d62','#fffffd');
insert into team (name , logo,base,main_color,second_color) values ('Brussels citizens','https://admin.touch-belgium.be/media/team_logos/citizens_logo.jpg','Auderghem','#7e2223','#ffcb53');
insert into team (name , logo,base,main_color,second_color) values ('BUC St Josse','https://admin.touch-belgium.be/media/team_logos/buc_logo.png','Saint-Josse','#ea2419','#ffffff');
insert into team (name , logo,base,main_color,second_color) values ('Gent Rugby','https://admin.touch-belgium.be/media/team_logos/gent_logo.png','Gand','#356b51','#ffffff');
insert into team (name , logo,base,main_color,second_color) values ('Kituro Rugby','https://admin.touch-belgium.be/media/team_logos/kituro_logo.jpg','Schaerbeek','#177644','#221d23');
insert into team (name , logo,base,main_color,second_color) values ('RC La Hulpe','https://admin.touch-belgium.be/media/team_logos/rclhlogo.jpg','La Hulpe','#2d4f34','#7d232d');
insert into team (name , logo,base,main_color,second_color) values ('Oudenaarde Rhinos','https://admin.touch-belgium.be/media/team_logos/rhinos_logo.jpeg','Audenarde','#000000','#ffffff');
insert into team (name , logo,base,main_color,second_color) values ('RC Luxembourg','https://www.s50static.com/cms/uploads/images/tinymce_images/774364ed8c2d84fdbf5d98f45e0e4c057cd9a_.png','Luxembourg','#00609d','#da394c');
insert into team (name , logo,base,main_color,second_color) values ('RFC Liège','https://admin.touch-belgium.be/media/team_logos/liege.jpg','Liege','#3d3d56','#b6474b'); 
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ernestus', 'Kirkup', 37, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jillane', 'Aspinwall', 39, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ajay', 'Minter', 21, 'Female', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Nady', 'Whittle', 18, 'Female', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hayward', 'Taverner', 40, 'Male', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Corenda', 'Marquet', 43, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hartwell', 'Crowson', 21, 'Male', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lambert', 'Jean', 20, 'Male', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Doug', 'Scawen', 32, 'Male', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Maddy', 'Moloney', 38, 'Male', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Vale', 'Braz', 22, 'Female', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Eustacia', 'Ledingham', 21, 'Female', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Murial', 'Megroff', 29, 'Female', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Domenic', 'Linck', 26, 'Male', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jack', 'Lalonde', 17, 'Male', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Valentine', 'Pickvance', 27, 'Male', 5, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Filmore', 'Alman', 21, 'Male', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Cyndie', 'Lucien', 26, 'Female', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Russ', 'Reddihough', 20, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Reamonn', 'Heinzel', 34, 'Male', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jilli', 'Abley', 21, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Paddie', 'Josipovitz', 44, 'Male', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lonnard', 'Hyde-Chambers', 23, 'Male', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Marcello', 'Blagden', 26, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Meriel', 'Edger', 34, 'Female', 5, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Shaine', 'Keford', 33, 'Female', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ethelbert', 'Doles', 39, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Colan', 'Michel', 34, 'Male', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Eleen', 'Garbott', 28, 'Female', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Doris', 'Wilmington', 19, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Laina', 'Woollam', 29, 'Female', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Calvin', 'Halloway', 31, 'Male', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kelli', 'Lyttle', 39, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Joshua', 'Jacketts', 40, 'Male', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kalil', 'Brugman', 29, 'Male', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jermayne', 'Dani', 22, 'Male', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Mathew', 'Muddle', 39, 'Male', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Edmund', 'McNamee', 25, 'Male', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kerrin', 'Manns', 40, 'Female', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Keri', 'Masser', 43, 'Female', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Freemon', 'Kocher', 35, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Cassy', 'Viles', 26, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tatiana', 'Welbourn', 41, 'Female', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Greta', 'Bruckent', 37, 'Female', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Talia', 'Kinmond', 37, 'Female', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Luther', 'Harome', 45, 'Male', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Marjory', 'Castanone', 40, 'Female', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Florentia', 'Kenwrick', 43, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Cathryn', 'Feldhorn', 45, 'Female', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Mathe', 'McQuilty', 42, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Baillie', 'Dickman', 41, 'Male', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Marian', 'Gamlyn', 32, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Henrieta', 'Kennett', 35, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Muffin', 'Gateley', 19, 'Male', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Joete', 'Checklin', 37, 'Female', 5, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hilary', 'Basile', 36, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Evania', 'Fullagar', 34, 'Female', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Anabal', 'Ricson', 25, 'Female', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Annamaria', 'Moorrud', 44, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Byron', 'Shevlane', 33, 'Male', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Edy', 'Pulbrook', 29, 'Female', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Matthew', 'Clemente', 44, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Charmane', 'Withringten', 26, 'Female', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Morley', 'McMichael', 30, 'Male', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Courtnay', 'Wadman', 44, 'Female', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Helen-elizabeth', 'Altofts', 29, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Catlaina', 'Crannis', 37, 'Female', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Wally', 'Winkle', 40, 'Male', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Juli', 'Tomaszkiewicz', 23, 'Female', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Colas', 'Baine', 32, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Keene', 'Halshaw', 22, 'Male', 5, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Artus', 'Tutill', 34, 'Male', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lindsy', 'Banfill', 43, 'Female', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kerrie', 'Kinsell', 18, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Edee', 'Cone', 34, 'Female', 5, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Parrnell', 'Aylmore', 17, 'Male', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tomasina', 'Duiged', 18, 'Female', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Izzy', 'Pratchett', 21, 'Male', 5, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Astrid', 'Belcher', 39, 'Female', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Latashia', 'Ricson', 44, 'Female', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Frayda', 'Mac Giany', 25, 'Female', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Derward', 'McClymont', 40, 'Male', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Bruce', 'Beevis', 45, 'Male', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Teador', 'Bengall', 20, 'Male', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Florry', 'Calafate', 22, 'Female', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Maxie', 'Newberry', 41, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Joshua', 'Pleven', 32, 'Male', 1, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ray', 'Wickersley', 44, 'Female', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jay', 'Mogie', 30, 'Male', 5, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Walker', 'Langlois', 33, 'Male', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Bradley', 'Cowlishaw', 19, 'Male', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hale', 'Fosten', 19, 'Male', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Damara', 'Murra', 45, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Daffi', 'Klesel', 37, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Xena', 'Gatland', 34, 'Female', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Chad', 'Karleman', 37, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tymothy', 'Albisser', 21, 'Male', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Berri', 'Biddy', 31, 'Female', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kliment', 'Spadollini', 35, 'Male', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tarrance', 'Amorine', 45, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Conrade', 'Byram', 21, 'Male', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kalila', 'Battey', 35, 'Female', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Loralee', 'Garm', 25, 'Female', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Rees', 'Danilenko', 17, 'Male', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Alysa', 'McKew', 45, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lucille', 'Aleksankin', 39, 'Female', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Adelaida', 'Tembridge', 21, 'Female', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Humphrey', 'Gerler', 31, 'Male', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Corinna', 'Petworth', 41, 'Female', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Thibaud', 'Cicchillo', 26, 'Male', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ewart', 'Avarne', 43, 'Male', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Giustino', 'Walne', 22, 'Male', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tommi', 'Eveling', 39, 'Female', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Uta', 'Mattiussi', 41, 'Female', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Darcee', 'Flaverty', 37, 'Female', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hendrik', 'Cockshutt', 38, 'Male', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Porter', 'Newman', 33, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Salmon', 'Cheng', 45, 'Male', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Yoshiko', 'Berriman', 42, 'Female', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Valeda', 'Arend', 43, 'Female', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Gabriello', 'Ryal', 19, 'Male', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Isaac', 'Rigby', 37, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Trstram', 'Huller', 28, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Edwin', 'Dunthorne', 42, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lindsay', 'Gheorghescu', 21, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lucien', 'Gammack', 45, 'Male', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Clarie', 'Pitson', 34, 'Female', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Adelbert', 'Levesley', 40, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Theo', 'Detheridge', 33, 'Male', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Miner', 'Strephan', 35, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Irvin', 'Naish', 43, 'Male', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Harwell', 'Kmieciak', 29, 'Male', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Holt', 'Hyslop', 23, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Camile', 'Phelip', 33, 'Female', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Adriena', 'Basset', 24, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lorne', 'Dulton', 37, 'Female', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hyacinthe', 'Woodings', 24, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Prudy', 'Gyrgorwicx', 27, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Bryan', 'Chisholme', 42, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Pauli', 'Benbough', 38, 'Female', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Albertina', 'Thirlwall', 36, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Langsdon', 'Josling', 31, 'Male', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Sargent', 'Scutchings', 41, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Maryellen', 'Kingswood', 27, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Rozanne', 'Lottrington', 28, 'Female', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hermine', 'Lavery', 43, 'Female', 5, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Gideon', 'Shillinglaw', 43, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kevon', 'Tumielli', 26, 'Male', 1, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Isiahi', 'Bonass', 31, 'Male', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Chico', 'Amdohr', 30, 'Male', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Darn', 'Omar', 38, 'Male', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Roscoe', 'Sindle', 32, 'Male', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Amalee', 'MacAdam', 21, 'Female', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Felizio', 'Trimmill', 27, 'Male', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Trixy', 'Olden', 34, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Noemi', 'Puckey', 17, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kora', 'Golightly', 38, 'Female', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ardelle', 'Sabine', 19, 'Female', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Dido', 'Tremethack', 41, 'Female', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Corabelle', 'Domino', 21, 'Female', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Rafi', 'Jollands', 36, 'Male', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Judah', 'Seathwright', 20, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Cletus', 'Herculeson', 26, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Winston', 'Papps', 26, 'Male', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Johnnie', 'Bettesworth', 19, 'Male', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Caspar', 'Newcome', 31, 'Male', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Celesta', 'Benedite', 45, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Norman', 'Blackburn', 20, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Carmon', 'Gleadhell', 28, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Letty', 'Morford', 28, 'Female', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Betsey', 'Tringham', 17, 'Female', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Cris', 'Gridon', 25, 'Female', 5, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ari', 'Eastmond', 29, 'Male', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Leonhard', 'Dransfield', 23, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Dorise', 'Blanche', 17, 'Female', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Melisandra', 'Rosetti', 38, 'Female', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Desi', 'Bream', 31, 'Male', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Zilvia', 'Tonbridge', 35, 'Female', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Dore', 'Castlake', 21, 'Male', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Malory', 'Willcock', 24, 'Female', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Andrej', 'Kuhndel', 36, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Poul', 'Gaspero', 24, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Frannie', 'Mc Meekan', 41, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Catrina', 'Goschalk', 34, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jacqueline', 'Wigmore', 26, 'Female', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Erminie', 'Audibert', 42, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Neely', 'Kindleside', 30, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Dulcy', 'Kiehl', 20, 'Female', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Woodman', 'Summerley', 22, 'Male', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Amery', 'Arling', 44, 'Male', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jedediah', 'Deabill', 35, 'Male', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Hayden', 'Suthworth', 27, 'Male', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Joceline', 'Seawright', 17, 'Female', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lorain', 'Hampshire', 42, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('De witt', 'MacKimmie', 38, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tiena', 'Noore', 39, 'Female', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kerry', 'Olligan', 37, 'Female', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Armin', 'Blooman', 23, 'Male', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ingram', 'Trahar', 26, 'Male', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Maxie', 'Lochhead', 19, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Torey', 'Dewitt', 33, 'Male', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Delphinia', 'Annakin', 39, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('August', 'Simcox', 30, 'Male', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ettore', 'Leddy', 18, 'Male', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Cornie', 'Virgo', 29, 'Male', 1, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Mellie', 'Myhill', 41, 'Female', 5, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Norry', 'Lampaert', 27, 'Male', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Carmella', 'Brunke', 32, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lloyd', 'Crumby', 42, 'Male', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kurtis', 'Tullett', 45, 'Male', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Molli', 'Berendsen', 33, 'Female', 5, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Wilma', 'McIlriach', 25, 'Female', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Caresse', 'Fridaye', 37, 'Female', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Maurine', 'Filippello', 33, 'Female', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Estelle', 'Croy', 26, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Padgett', 'Kingswoode', 25, 'Male', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Maddie', 'Goodlad', 44, 'Male', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Duke', 'Rosoman', 26, 'Male', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Flin', 'Pester', 38, 'Male', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Fernando', 'Torald', 27, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Vera', 'O'' Ronan', 37, 'Female', 10, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Dorie', 'Taveriner', 42, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Gerardo', 'Hollows', 24, 'Male', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Edan', 'Sneesby', 36, 'Male', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Miran', 'Kinforth', 44, 'Female', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kearney', 'Ausello', 21, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Adella', 'Pacey', 30, 'Female', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Engelbert', 'Feronet', 20, 'Male', 7, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Harmonie', 'Sellers', 30, 'Female', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kenna', 'Warrier', 41, 'Female', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Colan', 'Lewens', 41, 'Male', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Casey', 'Andries', 29, 'Male', 8, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Renata', 'Kynforth', 40, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Noel', 'Itzhayek', 43, 'Female', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Damaris', 'Dudding', 19, 'Female', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Venita', 'Cotterrill', 26, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tybie', 'Fishly', 43, 'Female', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Anson', 'Burnie', 35, 'Male', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Gnni', 'Vanichkin', 39, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Gisella', 'Osgar', 36, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Wyatt', 'Ingleton', 42, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Milo', 'Dallmann', 42, 'Male', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Garrik', 'Ingledow', 26, 'Male', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Nicolea', 'Hawford', 25, 'Female', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ingaborg', 'Wildey', 28, 'Female', 5, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kesley', 'Waker', 33, 'Female', 4, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jacquelin', 'Fust', 40, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Wilmer', 'Swanborough', 24, 'Male', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Emelen', 'Witherby', 38, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lisha', 'Cready', 39, 'Female', 9, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Barbara', 'Norvill', 32, 'Female', 10, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Sheridan', 'Bride', 38, 'Male', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Harp', 'Dainton', 23, 'Male', 8, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Fitzgerald', 'Brigge', 26, 'Male', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Lazarus', 'Vizard', 17, 'Male', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Madelon', 'Jerson', 28, 'Female', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jasmin', 'Heaselgrave', 35, 'Female', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Shawn', 'Coverley', 39, 'Male', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Joella', 'Greenstreet', 20, 'Female', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Penny', 'Babb', 35, 'Male', 6, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Prentiss', 'Nurny', 32, 'Male', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Myrilla', 'Lyptrit', 42, 'Female', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Abra', 'Gulliver', 29, 'Female', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Judy', 'Hayesman', 34, 'Female', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Alair', 'Pagan', 44, 'Male', 1, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Major', 'Monk', 40, 'Male', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Alix', 'Stathor', 28, 'Male', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Mollee', 'Dresser', 41, 'Female', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Abagael', 'Judron', 20, 'Female', 2, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Bette-ann', 'Mourbey', 19, 'Female', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Arman', 'Ladbury', 17, 'Male', 3, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Andre', 'Caudrelier', 18, 'Male', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Sarine', 'Giovannetti', 37, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Curry', 'Askin', 19, 'Male', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Emanuele', 'Chippindall', 37, 'Male', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Tod', 'Staker', 26, 'Male', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Normand', 'Gleed', 24, 'Male', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Kermit', 'Nanson', 36, 'Male', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Doy', 'Goncalo', 17, 'Male', 4, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Dorothea', 'Houtbie', 32, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Christian', 'Cuthbert', 35, 'Male', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jewel', 'Rosenthaler', 29, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Thomasa', 'Hazlegrove', 22, 'Female', 1, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Glynda', 'Horsefield', 32, 'Female', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Field', 'Grassot', 39, 'Male', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Laina', 'Gaytor', 23, 'Female', 5, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Ellissa', 'Rippon', 30, 'Female', 7, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Marybeth', 'Hamsley', 24, 'Female', 2, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Edwina', 'Garnsworth', 29, 'Female', 1, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Brewer', 'Dicey', 40, 'Male', 8, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Rich', 'Brunelleschi', 20, 'Male', 7, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Randee', 'Oxenbury', 42, 'Female', 3, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Liuka', 'Winsiowiecki', 17, 'Female', 6, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Robinia', 'Morgen', 43, 'Female', 10, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Gawain', 'Pryell', 18, 'Male', 9, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Rozamond', 'Aldis', 19, 'Female', 3, 'link');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Jacqui', 'Rowntree', 24, 'Female', 9, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Georgena', 'Truce', 17, 'Female', 2, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Theodor', 'Ciobotaro', 23, 'Male', 4, 'wing');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Way', 'Caro', 17, 'Male', 6, 'middle');
insert into player (first_name, last_name, age, gender, teamId, position) values ('Eric', 'KOEUT', 32, 'Male', 1, 'middle');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',1,5,7,1,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',6,4,4,9,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',9,2,4,10,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',7,8,5,15,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',10,3,4,5,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',4,1,14,6,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',6,8,12,2,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',2,5,9,6,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',10,7,10,4,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',3,9,1,10,'true');



insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',1,2,2,6,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',5,3,10,0,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',9,7,13,0,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',8,4,0,12,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',10,6,0,10,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',5,7,17,1,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',3,2,2,13,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',8,1,1,7,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',6,9,9,2,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',10,4,0,10,'true');


insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',1,3,6,1,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',2,7,17,0,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',9,4,0,11,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',5,6,2,10,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',10,8,0,10,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',9,8,6,5,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',3,7,8,3,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',6,2,7,9,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',5,4,3,13,'true');
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',10,1,0,10,'true');
insert into users (username, email, password, role, team_id) values ('crowbrey0', 'zwoollaston0@indiegogo.com', 'lBAZXT', 'admin', 2);
insert into users (username, email, password, role, team_id) values ('rmuddimer1', 'gkittman1@tumblr.com', 'HMPSYq0u', 'trainer', 5);
insert into users (username, email, password, role, team_id) values ('msewill2', 'cshegog2@exblog.jp', '4OzQLZFw', 'trainer', 6);
insert into users (username, email, password, role, team_id) values ('lmcgarahan3', 'ueyckelberg3@wiley.com', 'MfF9V7', 'trainer', 4);
insert into users (username, email, password, role, team_id) values ('pzuanazzi4', 'lpendrill4@google.pl', 'gn3HZgLJI', 'trainer', 7);
insert into users (username, email, password, role, team_id) values ('user1', 'user1@email.be', 'gn3HZgLJI', '''trainer''', 1);
