insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',1,5,7,1,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',6,4,4,9,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',9,2,4,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',7,8,5,15,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','23-10-2022',10,3,4,5,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',4,1,14,6,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',6,8,12,2,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',2,5,9,6,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',10,7,10,4,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','23-10-2022',3,9,1,10,'true')



insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',1,2,2,6,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',5,3,10,0,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',9,7,13,0,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',8,4,0,12,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','20-11-2022',10,6,0,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',5,7,17,1,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',3,2,2,13,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',8,1,1,7,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',6,9,9,2,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','20-11-2022',10,4,0,10,'true')


insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',1,3,6,1,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',2,7,17,0,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',9,4,0,11,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',5,6,2,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','12-02-2023',10,8,0,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',9,8,6,5,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',3,7,8,3,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',6,2,7,9,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',5,4,3,13,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','12-02-2023',10,1,0,10,'true')