insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','2022-10-23',1,5,7,1,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','2022-10-23',6,4,4,9,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','2022-10-23',9,2,4,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','2022-10-23',7,8,5,15,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,1,'Boitsfort', 'championship','2022-10-23',10,3,4,5,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','2022-10-23',4,1,14,6,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','2022-10-23',6,8,12,2,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','2022-10-23',2,5,9,6,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','2022-10-23',10,7,10,4,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,2,'Boitsfort', 'championship','2022-10-23',3,9,1,10,'true')



insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','2022-11-20',1,2,2,6,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','2022-11-20',5,3,10,0,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','2022-11-20',9,7,13,0,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','2022-11-20',8,4,0,12,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,3,'Gand', 'championship','2022-11-20',10,6,0,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','2022-11-20',5,7,17,1,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','2022-11-20',3,2,2,13,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','2022-11-20',8,1,1,7,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','2022-11-20',6,9,9,2,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,4,'Gand', 'championship','2022-11-20',10,4,0,10,'true')


insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','2023-02-12',1,3,6,1,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','2023-02-12',2,7,17,0,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','2023-02-12',9,4,0,11,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','2023-02-12',5,6,2,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,5,'Schaerbeek', 'championship','2023-02-12',10,8,0,10,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','2023-02-12',9,8,6,5,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','2023-02-12',3,7,8,3,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','2023-02-12',6,2,7,9,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','2023-02-12',5,4,3,13,'true')
insert into game (season_id,round,location,type,date,home_team_id,away_team_id,home_score,away_score,finish) values (1,6,'Schaerbeek', 'championship','2023-02-12',10,1,0,10,'true')