const games = [
    {
        id:1,
        round:1,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:1,
        away_team_id:5,
        home_score:7,
        away_score:1,
        finish:true
    },
    {
        id:2,
        round:1,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:6,
        away_team_id:4,
        home_score:4,
        away_score:9,
        finish:true
    },
    {
        id:3,
        round:1,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:9,
        away_team_id:2,
        home_score:4,
        away_score:10,
        finish:true
    },
    {
        id:4,
        round:1,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:7,
        away_team_id:8,
        home_score:5,
        away_score:15,
        finish:true
    },
    {
        id:5,
        round:1,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:10,
        away_team_id:3,
        home_score:4,
        away_score:5,
        finish:true
    },
    {
        id:6,
        round:2,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:4,
        away_team_id:1,
        home_score:14,
        away_score:6,
        finish:true
    },
    {
        id:7,
        round:2,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:6,
        away_team_id:8,
        home_score:12,
        away_score:2,
        finish:true
    },
    {
        id:8,
        round:2,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:2,
        away_team_id:5,
        home_score:9,
        away_score:6,
        finish:true
    },
    {
        id:9,
        round:2,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:10,
        away_team_id:7,
        home_score:10,
        away_score:4,
        finish:true
    },
    {
        id:10,
        round:2,
        localisation:"boisfort",
        type:"championship",
        date:"23/10/2022",
        home_team_id:3,
        away_team_id:9,
        home_score:1,
        away_score:10,
        finish:true
    },
]

export function getAllGame  (){
    return structuredClone(games)
}