[
    {
        id:1,
        leg:1,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:1,
        away_team_id:2,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:2,
        leg:1,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:3,
        away_team_id:4,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:3,
        leg:1,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:5,
        away_team_id:6,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:4,
        leg:1,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:7,
        away_team_id:8,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:5,
        leg:2,
        localisation:"oudenarde",
        type:"championship",
        date:"10/01/2023",
        home_team_id:1,
        away_team_id:2,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:6,
        leg:2,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:1,
        away_team_id:2,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:7,
        leg:2,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:1,
        away_team_id:2,
        home_score:10,
        away_score:2,
        finish:true
    },
    {
        id:8,
        leg:2,
        localisation:"brussels",
        type:"championship",
        date:"10/01/2023",
        home_team_id:1,
        away_team_id:2,
        home_score:10,
        away_score:2,
        finish:true
    }
]